version: "3.7"
services:

  apache:
    container_name: ${APPLICATION_NAME:-myDockerApp}_webserver
    build:
      context: .
      dockerfile: ./.docker/webserver/Dockerfile
    volumes:
      # Allow to sync the /src folder of the development machine to the
      - ./src:/var/www/html
    depends_on:
      - php
    expose:
      - ${APACHE_PORT:-8080}
    ports:
      - ${APACHE_PORT:-8080}:80

  php:
    container_name: ${APPLICATION_NAME:-myDockerApp}_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        - APPLICATION_NAME=${APPLICATION_NAME:-myDockerApp}
        - PHP_VERSION=${PHP_VERSION:-8.0}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE:-0}
    environment:
        # Define OS environment variables; used by ./.docker/php/conf.d/opcache.ini
        # Using this syntax (and not creating the variable in the Dockerfile make easy
        # to change a setting without the need to recreate the image)
        #! Values comes from the .env file and, if not present, use a default value optimized for PROD
        OPCACHE_ENABLE: ${OPCACHE_ENABLE:-1}
        OPCACHE_ENABLE_CLI: ${OPCACHE_ENABLE_CLI:-1}
        OPCACHE_MAX_ACCELERATED_FILES: ${OPCACHE_MAX_ACCELERATED_FILES:-50000}
        OPCACHE_MEMORY_CONSUMPTION: ${OPCACHE_MEMORY_CONSUMPTION:-1024}
        OPCACHE_VALIDATE_TIMESTAMPS: ${OPCACHE_VALIDATE_TIMESTAMPS:-0}
    volumes:
      # Allow to sync the /src folder of the development machine to the
      - ./src:/var/www/html
