version: "3.7"
services:

  apache:
    container_name: ${APPLICATION_NAME}_webserver
    build:
      context: .
      dockerfile: ./.docker/webserver/Dockerfile
    volumes:
      # Allow to sync the /src folder of the development machine to the
      - ./src:/var/www/html
    depends_on:
      - php
    expose:
      - ${APACHE_PORT}
    ports:
      - ${APACHE_PORT}:80

  php:
    container_name: ${APPLICATION_NAME}_php
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        - APPLICATION_NAME=${APPLICATION_NAME}
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_OPCACHE=${INSTALL_OPCACHE}
        - OPCACHE_MEMORY_CONSUMPTION=${OPCACHE_MEMORY_CONSUMPTION}
    volumes:
      # Allow to sync the /src folder of the development machine to the
      - ./src:/var/www/html
